name: Tests

on:
  push

jobs:
  trie-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pytest
        run: pip install pytest
      - name: Build trie 
        run: |
          mkdir tests/trie/build
          cd tests/trie/build
          cmake ..
          make
      - name: Run test
        run: |
          cd tests/trie
          pytest .

  lexer-test:
    needs: trie-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pytest
        run: pip install pytest
      - name: Build lexer
        run: |
          mkdir tests/lexer/build
          cd tests/lexer/build
          cmake ..
          make
      - name: Run test
        run: |
          cd tests/lexer
          pytest .

  sintex-test:
    needs: lexer-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pytest
        run: pip install pytest
      - name: Build sintex
        run: |
          mkdir tests/sintex/build
          cd tests/sintex/build
          cmake ..
          make
      - name: Run test
        run: |
          cd tests/sintex
          pytest .

  segment-tree-test:
    needs: sintex-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pytest
        run: pip install pytest
      - name: Build yuhan segment-tree
        run: |
          mkdir tests/segment-tree/build
          cd tests/segment-tree/build
          cmake ..
          make
      - name: Build segment tree
        run: |
          cd tests/segment-tree
          g++ segment-tree.cpp -o segment-tree
      - name: Run test
        run: |
          cd tests/segment-tree
          pytest .

  sort-test:
    needs: sintex-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install pytest
        run: pip install pytest
      - name: Build yuhan sort
        run: |
          mkdir tests/sort/build
          cd tests/sort/build
          cmake ..
          make
      - name: Build sort
        run: |
          cd tests/sort
          g++ sort.cpp -o sort
      - name: Run test
        run: |
          cd tests/sort
          pytest .
